// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(code), Name = "IX_command", IsUnique = true)]
    public partial class CommandVM
    {
        public string Command { get; set; }
        public int Code { get; set; }
    }
}