// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(code), Name = "IX_character", IsUnique = true)]
    //[Index(nameof(code_name), Name = "IX_character_code_Unique", IsUnique = true)]
    public partial class Character : BaseDataEntity<Character_name>
    {
        public Character()
        {
            SetApp(TableName.Character);
            NameSet = new HashSet<Character_name>();

        }
    }
}