// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(code), Name = "IX_character", IsUnique = true)]
    [Index(nameof(code_name), Name = "IX_character_code_Unique", IsUnique = true)]
    public partial class character
    {
        public character()
        {
            Move = new HashSet<Move>();
            moveSubType = new HashSet<moveSubType>();
            moveText = new HashSet<moveText>();
        }

        [Key]
        public int id { get; set; }
        public byte code { get; set; }
        [Required]
        [StringLength(3)]
        public string code_name { get; set; }
        public byte season { get; set; }
        [Required]
        public string description { get; set; }

        public virtual ICollection<Move> Move { get; set; }
        public virtual ICollection<moveSubType> moveSubType { get; set; }
        public virtual ICollection<moveText> moveText { get; set; }
    }
}