// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(code), Name = "IX_command", IsUnique = true)]
    public partial class command
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(4)]
        public string code { get; set; }
        [Required]
        [Column("command")]
        public string command1 { get; set; }
        [Required]
        public string key { get; set; }
    }
}