// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(command_code), nameof(language_code), Name = "IX_command_name", IsUnique = true)]
    public partial class Command_name : BaseNameEntity
    {
        public Command_name()
        {
            SetApp(TableName.HitType_name);
        }

       
        [NotMapped]
        public new int Base_code { get; set; }
        
        public string CommandCode { get; set; }

    }
}