// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(code), Name = "IX_command", IsUnique = true)]
    public partial class Command : BaseDataEntity<Command_name>
    {
        public Command()
        {
            SetApp(TableName.Command);
            NameSet = new HashSet<Command_name>();
        }

        [NotMapped]
        public new int Number { get; set; }

        [NotMapped]
        public new string Description { get; set; }

        [NotMapped]
        public new int Code { get; set; }

        public string commandCode { get; set; }

        [Required]
        [Column("command")]
        public string command { get; set; }
        [Required]
        public string key { get; set; }
    }
}