// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(code), Name = "IX_hitType", IsUnique = true)]
    [Index(nameof(number), Name = "IX_hitType_1", IsUnique = true)]
    public partial class hitType
    {
        public hitType()
        {
            hitType_name = new HashSet<hitType_name>();
            move_datacounterType_codeNavigation = new HashSet<move_data>();
            move_dataguardType_codeNavigation = new HashSet<move_data>();
            move_datahitType_codeNavigation = new HashSet<move_data>();
            move_datastartType_codeNavigation = new HashSet<move_data>();
        }

        [Key]
        public int id { get; set; }
        public int code { get; set; }
        [Required]
        public string description { get; set; }
        public byte number { get; set; }

        public virtual ICollection<hitType_name> hitType_name { get; set; }
        public virtual ICollection<move_data> move_datacounterType_codeNavigation { get; set; }
        public virtual ICollection<move_data> move_dataguardType_codeNavigation { get; set; }
        public virtual ICollection<move_data> move_datahitType_codeNavigation { get; set; }
        public virtual ICollection<move_data> move_datastartType_codeNavigation { get; set; }
    }
}