// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    public partial class hitType_name
    {
        [Key]
        public int id { get; set; }
        public int hitType_code { get; set; }
        [Required]
        [StringLength(2)]
        public string language_code { get; set; }
        [Required]
        public string name { get; set; }
        [Column("checked")]
        public bool _checked { get; set; }

        public virtual hitType hitType_codeNavigation { get; set; }
    }
}