// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(code), Name = "IX_language", IsUnique = true)]
    public partial class language
    {
        public language()
        {
            StateGroup_name = new HashSet<StateGroup_name>();
            State_name = new HashSet<State_name>();
            character_name = new HashSet<character_name>();
            command_name = new HashSet<command_name>();
            moveSubType_name = new HashSet<moveSubType_name>();
            moveText_name = new HashSet<moveText_name>();
            moveType_name = new HashSet<moveType_name>();
            move_command_name = new HashSet<move_command_name>();
            move_name = new HashSet<move_name>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(2)]
        public string code { get; set; }
        [Required]
        public string name { get; set; }
        public byte number { get; set; }

        public virtual ICollection<StateGroup_name> StateGroup_name { get; set; }
        public virtual ICollection<State_name> State_name { get; set; }
        public virtual ICollection<character_name> character_name { get; set; }
        public virtual ICollection<command_name> command_name { get; set; }
        public virtual ICollection<moveSubType_name> moveSubType_name { get; set; }
        public virtual ICollection<moveText_name> moveText_name { get; set; }
        public virtual ICollection<moveType_name> moveType_name { get; set; }
        public virtual ICollection<move_command_name> move_command_name { get; set; }
        public virtual ICollection<move_name> move_name { get; set; }
    }
}