// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(code), Name = "IX_language", IsUnique = true)]
    public partial class Language : BaseDataEntity
    {
        public Language()
        {
            SetApp(TableName.Language);
            //StateGroup_name = new HashSet<StateGroup_name>();
            //State_name = new HashSet<State_name>();
            //character_name = new HashSet<Character_name>();
            //command_name = new HashSet<Command_name>();
            //moveSubType_name = new HashSet<MoveSubType_name>();
            //moveText_name = new HashSet<MoveText_name>();
            //moveType_name = new HashSet<MoveType_name>();
            //move_command_name = new HashSet<Move_command_name>();
            //move_name = new HashSet<Move_name>();
        }


        //[Required]
        //[StringLength(2)]
                
        public string Language_code { get; set; }
        //[Required]
        //public string name { get; set; }

        //public virtual ICollection<StateGroup_name> StateGroup_name { get; set; }
        //public virtual ICollection<State_name> State_name { get; set; }
        //public virtual ICollection<Character_name> character_name { get; set; }
        //public virtual ICollection<Command_name> command_name { get; set; }
        //public virtual ICollection<MoveSubType_name> moveSubType_name { get; set; }
        //public virtual ICollection<MoveText_name> moveText_name { get; set; }
        //public virtual ICollection<MoveType_name> moveType_name { get; set; }
        //public virtual ICollection<Move_command_name> move_command_name { get; set; }
        //public virtual ICollection<Move_name> move_name { get; set; }
    }
}