// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(character_code), nameof(number), Name = "IX_Move", IsUnique = true)]
    [Index(nameof(code), Name = "IX_Move_1", IsUnique = true)]
    public partial class Move
    {
        public Move()
        {
            move_command_name = new HashSet<Move_command_name>();
            move_name = new HashSet<Move_name>();
        }

        [Key]
        public int id { get; set; }
        public int code { get; set; }
        public byte character_code { get; set; }
        public short number { get; set; }
        [Required]
        public string description { get; set; }
        [Column(TypeName = "decimal(4, 2)")]
        public decimal? version { get; set; }

        public virtual Character character_codeNavigation { get; set; }
        [ForeignKey(nameof(version))]
        [InverseProperty(nameof(TekkenVersion.Move))]
        public virtual TekkenVersion versionNavigation { get; set; }
        public virtual Move_command Move_command { get; set; }
        public virtual Move_data move_data { get; set; }
        public virtual ICollection<Move_command_name> move_command_name { get; set; }
        public virtual ICollection<Move_name> move_name { get; set; }
    }
}