// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(language_code), nameof(Move_Command_code), Name = "IX_move_command", IsUnique = true)]
    public partial class move_command_name
    {
        [Key]
        public int id { get; set; }
        public int Move_Command_code { get; set; }
        [Required]
        [StringLength(2)]
        public string language_code { get; set; }
        [Required]
        public string name { get; set; }
        [Column("checked")]
        public bool _checked { get; set; }

        public virtual Move Move_Command_codeNavigation { get; set; }
        public virtual language language_codeNavigation { get; set; }
    }
}