// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(move_code), Name = "IX_Move_command_1", IsUnique = true)]
    public partial class MoveCommand : BaseDataEntity
    {
        public MoveCommand ()
        {
            SetApp(TableName.MoveCommand);
        }

        
        [NotMapped]
        public new int Number { get; set; }
        public int Base_code
        {
            get
            {
                return base.Base_code;
            }
            set
            {
                base.Base_code = value;
            }
        }

        [Required]
        public string Command { get; set; }

        public virtual Move Move { get; set; }
    }
}