// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(move_code), Name = "IX_Move_command_1", IsUnique = true)]
    public partial class Move_command
    {
        [Key]
        public int id { get; set; }
        public int move_code { get; set; }
        [Required]
        public string command { get; set; }

        public virtual Move move_codeNavigation { get; set; }
    }
}