// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(character_code), nameof(number), Name = "IX_moveText_character_code_number", IsUnique = true)]
    [Index(nameof(code), Name = "IX_moveText_code", IsUnique = true)]
    public partial class moveText
    {
        public moveText()
        {
            moveText_name = new HashSet<moveText_name>();
        }

        [Key]
        public int id { get; set; }
        public int code { get; set; }
        public byte character_code { get; set; }
        public byte number { get; set; }
        [Required]
        public string description { get; set; }

        public virtual character character_codeNavigation { get; set; }
        public virtual ICollection<moveText_name> moveText_name { get; set; }
    }
}