// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(Move_Data_Code), nameof(language_code), Name = "IX_Move_Data_Name", IsUnique = true)]
    public partial class Move_Data_Name
    {
        [Key]
        public int id { get; set; }
        public int Move_Data_Code { get; set; }
        public string moveType_name { get; set; }
        public string moveSubType_name { get; set; }
        public string StartType_name { get; set; }
        public string Guardtype_name { get; set; }
        public string hitType_name { get; set; }
        public string counterType_name { get; set; }
        public string note_name { get; set; }
        [Required]
        [StringLength(2)]
        public string language_code { get; set; }
        [Column("checked")]
        public bool _checked { get; set; }

        public virtual Move_data Move_Data_CodeNavigation { get; set; }
    }
}