// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace TekkenApp.Models
{
    ///[Index(nameof(Move_Code), Name = "IX_move_data", IsUnique = true)]
    public partial class MoveVideo : BaseDataEntity
    {
        public MoveVideo()
        {
            SetApp(TableName.MoveVideo);
        }


        [NotMapped]
        public new int Number { get; set; }

        public int Base_code
        {
            get
            {
                return base.Base_code;
            }
            set
            {
                base.Base_code = value;
            }
        }
        public string YoutubeId { get; set; }
        public string YoutubeTitle { get; set; }
        public string YoutubeUrl { get; set; }
        public string YoutubeDescription { get; set; }
        public string YoutubeTag{ get; set; }
        public string FileName { get; set; }

        public virtual Move Move { get; set; }
    }
}