// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(move_code), Name = "IX_Move_command_1", IsUnique = true)]
    public partial class MoveCommand : BaseDataEntity<MoveCommand_name>
    {
        public MoveCommand ()
        {
            SetApp(TableName.MoveCommand);
            NameSet = new HashSet<MoveCommand_name>();
        }
        
        [NotMapped]
        public new int Number { get; set; }
        public int Base_Code { get; set; }

        [Required]
        public string Command { get; set; }

        public virtual Move Move { get; set; }
    }
}