// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(Move_Code), Name = "IX_move_data", IsUnique = true)]
    public partial class move_data
    {
        public move_data()
        {
            Move_Data_Name = new HashSet<Move_Data_Name>();
        }

        [Key]
        public int id { get; set; }
        public int Move_Code { get; set; }
        public int? moveType_code { get; set; }
        public int? moveSubType_code { get; set; }
        public byte hitCount { get; set; }
        [Required]
        public string hitLevel { get; set; }
        public short damage { get; set; }
        public short startFrame { get; set; }
        public string startFrame_Display { get; set; }
        public int? startType_code { get; set; }
        public short guardFrame { get; set; }
        public string guardFrame_Display { get; set; }
        public int guardType_code { get; set; }
        public short hitFrame { get; set; }
        public string hitFrame_Display { get; set; }
        public int hitType_code { get; set; }
        public short counterFrame { get; set; }
        public string counterFrame_Display { get; set; }
        public int counterType_code { get; set; }
        public string breakThrow { get; set; }
        public string afterBreak { get; set; }
        public bool homing { get; set; }
        public bool powerCrush { get; set; }
        public bool technicallyCrouching { get; set; }
        public bool technicallyJumping { get; set; }
        public bool tailSpin { get; set; }
        public bool wallSplat { get; set; }
        public string note { get; set; }
        [Column(TypeName = "decimal(4, 2)")]
        public decimal? version { get; set; }

        public virtual Move Move_CodeNavigation { get; set; }
        public virtual hitType counterType_codeNavigation { get; set; }
        public virtual hitType guardType_codeNavigation { get; set; }
        public virtual hitType hitType_codeNavigation { get; set; }
        public virtual moveSubType moveSubType_codeNavigation { get; set; }
        public virtual moveType moveType_codeNavigation { get; set; }
        public virtual hitType startType_codeNavigation { get; set; }
        public virtual ICollection<Move_Data_Name> Move_Data_Name { get; set; }
    }
}