// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(code), nameof(number), Name = "IX_moveType_1", IsUnique = true)]
    [Index(nameof(code), Name = "IX_moveType_code_unique", IsUnique = true)]
    public partial class moveType
    {
        public moveType()
        {
            moveType_name = new HashSet<moveType_name>();
            move_data = new HashSet<move_data>();
        }

        [Key]
        public int id { get; set; }
        public int code { get; set; }
        public byte number { get; set; }
        [Required]
        public string description { get; set; }

        public virtual ICollection<moveType_name> moveType_name { get; set; }
        public virtual ICollection<move_data> move_data { get; set; }
    }
}