// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

namespace TekkenApp.Models
{
    //[Index(nameof(character_code), nameof(number), Name = "IX_Move", IsUnique = true)]
    //[Index(nameof(code), Name = "IX_Move_1", IsUnique = true)]
    public partial class Move : BaseDataEntity
    {
        public Move()
        {
            SetApp(TableName.Move);
        }
        public new int Character_code
        {
            get
            {
                return base.Character_code;
            }
            set
            {
                base.Character_code = value;
            }
        }

        //[Column(TypeName = "decimal(4, 2)")]
        public double? version { get; set; }

        public virtual MoveCommand MoveCommand { get; set; }

        public virtual MoveData MoveData { get; set; }

        //public virtual Character character_codeNavigation { get; set; }
        //[ForeignKey(nameof(version))]
        //[InverseProperty(nameof(TekkenVersion.Move))]
        //public virtual TekkenVersion versionNavigation { get; set; }
        //public virtual MoveData move_data { get; set; }
        //public virtual ICollection<Move_command_name> move_command_name { get; set; }
        //public virtual ICollection<Move_name> move_name { get; set; }
    }
}