// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(moveSubType_code), nameof(language_code), Name = "IX_moveSubType_name", IsUnique = true)]
    public partial class moveSubType_name
    {
        [Key]
        public int id { get; set; }
        public int moveSubType_code { get; set; }
        [Required]
        [StringLength(2)]
        public string language_code { get; set; }
        [Required]
        public string name { get; set; }
        public bool Checked { get; set; }

        public virtual language language_codeNavigation { get; set; }
        public virtual moveSubType moveSubType_codeNavigation { get; set; }
    }
}