// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(Code), Name = "IX_State", IsUnique = true)]
    //[Index(nameof(StateGroup_code), nameof(number), Name = "IX_State_1", IsUnique = true)]
    public partial class State : BaseDataEntity
    {
        public State()
        {
        }
        //public new int StateGroup_code { get; set; }
        public new int StateGroup_code
        {
            get
            {
                return base.StateGroup_code;
            }
            set
            {
                base.StateGroup_code = value;
            }
        }

        //public virtual StateGroup StateGroup_codeNavigation { get; set; }
        //public virtual ICollection<State_name> State_name { get; set; }
    }
}