// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

#nullable disable

namespace TekkenApp.Models
{
    [Index(nameof(Code), Name = "IX_State", IsUnique = true)]
    //[Index(nameof(StateGroup_code), nameof(number), Name = "IX_State_1", IsUnique = true)]
    public partial class State : BaseDataEntity
    {
        public State()
        {
            NameSet = new HashSet<State_name>();
        }
        public new ICollection<State_name> NameSet { get; set; }
        public new int StateGroup_code { get; set; }

        //public virtual StateGroup StateGroup_codeNavigation { get; set; }
        //public virtual ICollection<State_name> State_name { get; set; }
    }
}