// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TekkenApp.Models
{
    public partial class TekkenVersion
    {
        public TekkenVersion()
        {
            Move = new HashSet<Move>();
        }

        public int? ID { get; set; }
        [Key]
        //[Column(TypeName = "decimal(4, 2)")]
        public decimal version { get; set; }
        public int season { get; set; }
        [Column(TypeName = "date")]
        public DateTime updateDate { get; set; }

        //[InverseProperty("versionNavigation")]
        public virtual ICollection<Move> Move { get; set; }
    }
}