// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TestEF
{
    public partial class CharacterName
    {
        public int Id { get; set; }
        public int CharacterCode { get; set; }
        public string LanguageCode { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
    }
}