// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace TestEF
{
    public partial class Character
    {
        public int Id { get; set; }
        public byte Code { get; set; }
        public string CodeName { get; set; }
        public byte Season { get; set; }
        public string Description { get; set; }
    }
}