// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("character_name")]
    [Index(nameof(CharacterCode), nameof(LanguageCode), Name = "IX_character_name", IsUnique = true)]
    public partial class CharacterName
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("character_code")]
        public int CharacterCode { get; set; }
        [Required]
        [Column("language_code")]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        [Required]
        [Column("fullName")]
        public string FullName { get; set; }

        public virtual Language LanguageCodeNavigation { get; set; }
    }
}