// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("command")]
    [Index(nameof(Code), Name = "IX_command", IsUnique = true)]
    public partial class Command
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("code")]
        [StringLength(4)]
        public string Code { get; set; }
        [Required]
        [Column("command")]
        public string Command1 { get; set; }
        [Required]
        [Column("key")]
        public string Key { get; set; }
    }
}