// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("hitType")]
    [Index(nameof(Code), Name = "IX_hitType", IsUnique = true)]
    [Index(nameof(Number), Name = "IX_hitType_1", IsUnique = true)]
    public partial class HitType
    {
        public HitType()
        {
            HitTypeName = new HashSet<HitTypeName>();
            MoveDataCounterTypeCodeNavigation = new HashSet<MoveData>();
            MoveDataGuardTypeCodeNavigation = new HashSet<MoveData>();
            MoveDataHitTypeCodeNavigation = new HashSet<MoveData>();
            MoveDataStartTypeCodeNavigation = new HashSet<MoveData>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("code")]
        public int Code { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }
        [Column("number")]
        public byte Number { get; set; }

        public virtual ICollection<HitTypeName> HitTypeName { get; set; }
        public virtual ICollection<MoveData> MoveDataCounterTypeCodeNavigation { get; set; }
        public virtual ICollection<MoveData> MoveDataGuardTypeCodeNavigation { get; set; }
        public virtual ICollection<MoveData> MoveDataHitTypeCodeNavigation { get; set; }
        public virtual ICollection<MoveData> MoveDataStartTypeCodeNavigation { get; set; }
    }
}