// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("hitType_name")]
    public partial class HitTypeName
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("hitType_code")]
        public int HitTypeCode { get; set; }
        [Required]
        [Column("language_code")]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        [Column("checked")]
        public bool Checked { get; set; }

        public virtual HitType HitTypeCodeNavigation { get; set; }
    }
}