// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("language")]
    [Index(nameof(Code), Name = "IX_language", IsUnique = true)]
    public partial class Language
    {
        public Language()
        {
            CharacterName = new HashSet<CharacterName>();
            CommandName = new HashSet<CommandName>();
            MoveCommandName = new HashSet<MoveCommandName>();
            MoveName = new HashSet<MoveName>();
            MoveSubTypeName = new HashSet<MoveSubTypeName>();
            MoveTextName = new HashSet<MoveTextName>();
            MoveTypeName = new HashSet<MoveTypeName>();
            StateGroupName = new HashSet<StateGroupName>();
            StateName = new HashSet<StateName>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("code")]
        [StringLength(2)]
        public string Code { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        [Column("number")]
        public byte Number { get; set; }

        public virtual ICollection<CharacterName> CharacterName { get; set; }
        public virtual ICollection<CommandName> CommandName { get; set; }
        public virtual ICollection<MoveCommandName> MoveCommandName { get; set; }
        public virtual ICollection<MoveName> MoveName { get; set; }
        public virtual ICollection<MoveSubTypeName> MoveSubTypeName { get; set; }
        public virtual ICollection<MoveTextName> MoveTextName { get; set; }
        public virtual ICollection<MoveTypeName> MoveTypeName { get; set; }
        public virtual ICollection<StateGroupName> StateGroupName { get; set; }
        public virtual ICollection<StateName> StateName { get; set; }
    }
}