// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("moveText")]
    [Index(nameof(CharacterCode), nameof(Number), Name = "IX_moveText_character_code_number", IsUnique = true)]
    [Index(nameof(Code), Name = "IX_moveText_code", IsUnique = true)]
    public partial class MoveText
    {
        public MoveText()
        {
            MoveTextName = new HashSet<MoveTextName>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("code")]
        public int Code { get; set; }
        [Column("character_code")]
        public byte CharacterCode { get; set; }
        [Column("number")]
        public byte Number { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }

        public virtual Character CharacterCodeNavigation { get; set; }
        public virtual ICollection<MoveTextName> MoveTextName { get; set; }
    }
}