// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("moveType")]
    [Index(nameof(Code), nameof(Number), Name = "IX_moveType_1", IsUnique = true)]
    [Index(nameof(Code), Name = "IX_moveType_code_unique", IsUnique = true)]
    public partial class MoveType
    {
        public MoveType()
        {
            MoveData = new HashSet<MoveData>();
            MoveTypeName = new HashSet<MoveTypeName>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("code")]
        public int Code { get; set; }
        [Column("number")]
        public byte Number { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }

        public virtual ICollection<MoveData> MoveData { get; set; }
        public virtual ICollection<MoveTypeName> MoveTypeName { get; set; }
    }
}