// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("Move_command")]
    [Index(nameof(MoveCode), Name = "IX_Move_command_1", IsUnique = true)]
    public partial class MoveCommand
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("move_code")]
        public int MoveCode { get; set; }
        [Required]
        [Column("command")]
        public string Command { get; set; }

        public virtual Move MoveCodeNavigation { get; set; }
    }
}