// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("Move_Data_Name")]
    [Index(nameof(MoveDataCode), nameof(LanguageCode), Name = "IX_Move_Data_Name", IsUnique = true)]
    public partial class MoveDataName
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("Move_Data_Code")]
        public int MoveDataCode { get; set; }
        [Column("moveType_name")]
        public string MoveTypeName { get; set; }
        [Column("moveSubType_name")]
        public string MoveSubTypeName { get; set; }
        [Column("StartType_name")]
        public string StartTypeName { get; set; }
        [Column("Guardtype_name")]
        public string GuardtypeName { get; set; }
        [Column("hitType_name")]
        public string HitTypeName { get; set; }
        [Column("counterType_name")]
        public string CounterTypeName { get; set; }
        [Column("note_name")]
        public string NoteName { get; set; }
        [Required]
        [Column("language_code")]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        [Column("checked")]
        public bool Checked { get; set; }

        public virtual MoveData MoveDataCodeNavigation { get; set; }
    }
}