// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Index(nameof(CharacterCode), nameof(Number), Name = "IX_Move", IsUnique = true)]
    [Index(nameof(Code), Name = "IX_Move_1", IsUnique = true)]
    public partial class Move
    {
        public Move()
        {
            MoveCommandName = new HashSet<MoveCommandName>();
            MoveName = new HashSet<MoveName>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("code")]
        public int Code { get; set; }
        [Column("character_code")]
        public byte CharacterCode { get; set; }
        [Column("number")]
        public short Number { get; set; }
        [Required]
        [Column("description")]
        public string Description { get; set; }
        [Column("version", TypeName = "decimal(4, 2)")]
        public decimal? Version { get; set; }

        public virtual Character CharacterCodeNavigation { get; set; }
        [ForeignKey(nameof(Version))]
        [InverseProperty(nameof(TekkenVersion.Move))]
        public virtual TekkenVersion VersionNavigation { get; set; }
        public virtual MoveCommand MoveCommand { get; set; }
        public virtual MoveData MoveData { get; set; }
        public virtual ICollection<MoveCommandName> MoveCommandName { get; set; }
        public virtual ICollection<MoveName> MoveName { get; set; }
    }
}