// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("moveText_name")]
    [Index(nameof(MoveTextCode), nameof(LanguageCode), Name = "IX_moveText_name", IsUnique = true)]
    public partial class MoveTextName
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("moveText_code")]
        public int MoveTextCode { get; set; }
        [Required]
        [Column("language_code")]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        public bool Checked { get; set; }

        public virtual Language LanguageCodeNavigation { get; set; }
        public virtual MoveText MoveTextCodeNavigation { get; set; }
    }
}