// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("moveType_name")]
    [Index(nameof(LanguageCode), nameof(MoveTypeCode), Name = "IX_moveType_name", IsUnique = true)]
    public partial class MoveTypeName
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("moveType_code")]
        public int MoveTypeCode { get; set; }
        [Required]
        [Column("language_code")]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        public bool Checked { get; set; }

        public virtual Language LanguageCodeNavigation { get; set; }
        public virtual MoveType MoveTypeCodeNavigation { get; set; }
    }
}