// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("State_name")]
    [Index(nameof(StateCode), nameof(LanguageCode), Name = "IX_State_name", IsUnique = true)]
    public partial class StateName
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("state_code")]
        public int StateCode { get; set; }
        [Required]
        [Column("language_code")]
        [StringLength(2)]
        public string LanguageCode { get; set; }
        [Required]
        [Column("name")]
        public string Name { get; set; }
        [Column("checked")]
        public bool Checked { get; set; }

        public virtual Language LanguageCodeNavigation { get; set; }
        public virtual State StateCodeNavigation { get; set; }
    }
}