// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Models.Models
{
    [Table("tekkenVersion")]
    public partial class TekkenVersion
    {
        public TekkenVersion()
        {
            Move = new HashSet<Move>();
        }

        [Column("ID")]
        public int? Id { get; set; }
        [Key]
        [Column("version", TypeName = "decimal(4, 2)")]
        public decimal Version { get; set; }
        [Column("season")]
        public byte Season { get; set; }
        [Column("updateDate", TypeName = "date")]
        public DateTime UpdateDate { get; set; }

        [InverseProperty("VersionNavigation")]
        public virtual ICollection<Move> Move { get; set; }
    }
}